### ISSUE TITLE
Fix sqlite alter table error

### ISSUE THREAD

**Issue by faishal** [rtCamp/media-node#13]
Every time when media-node server start, it is throwing following sqlite error

```
Error: SQLITE_ERROR: duplicate column name: duration
Error: SQLITE_ERROR: duplicate column name: thumbs
```

**Comment by shaneholloman** [comment]
This happens during installation as well
 So not sure if my install was complete or not

I say this because https://nauti.nz:1023 fails to open. Port is are open but no go (assuming the default port is 1023 since I wasn't asked during the install to pick a port

**Comment by faishal** [comment]
@shaneholloman you can ignore this warning, it doesn't effect the installation 

Please check if your node server is up and running or not !
