### ISSUE TITLE
Error after Copying Media Node

### ISSUE THREAD

**Issue by SpotMedias** [rtCamp/media-node#19]
Hi,

I already made some updates to be able to install Media Node on a Ubuntu 14.04.2 LTS but am stuck and can't find any solutions to resolve this error : 
## 

Cloning into 'media-node'...
remote: Counting objects: 1228, done.
remote: Total 1228 (delta 0), reused 0 (delta 0), pack-reused 1228
Receiving objects: 100% (1228/1228), 414.09 KiB | 0 bytes/s, done.
Resolving deltas: 100% (424/424), done.
Checking connectivity... done.
‘media-node/ffmpeg_server.js’ -> ‘/root/media-node/ffmpeg_server.js’
‘media-node/install.sh’ -> ‘/root/media-node/install.sh’
‘media-node/package.json’ -> ‘/root/media-node/package.json’
‘media-node/README.md’ -> ‘/root/media-node/README.md’
‘media-node/setup’ -> ‘/root/media-node/setup’
‘media-node/setup/ubuntu.sh’ -> ‘/root/media-node/setup/ubuntu.sh’
‘media-node/setup/check.sh’ -> ‘/root/media-node/setup/check.sh’
‘media-node/setup/update.sh’ -> ‘/root/media-node/setup/update.sh’
‘media-node/setup/redhat.sh’ -> ‘/root/media-node/setup/redhat.sh’
‘media-node/setup/debian.sh’ -> ‘/root/media-node/setup/debian.sh’
‘media-node/setup/redhat5.sh’ -> ‘/root/media-node/setup/redhat5.sh’
‘media-node/.git’ -> ‘/root/media-node/.git’
‘media-node/.git/info’ -> ‘/root/media-node/.git/info’
‘media-node/.git/info/exclude’ -> ‘/root/media-node/.git/info/exclude’
‘media-node/.git/branches’ -> ‘/root/media-node/.git/branches’
‘media-node/.git/config’ -> ‘/root/media-node/.git/config’
‘media-node/.git/logs’ -> ‘/root/media-node/.git/logs’
‘media-node/.git/logs/HEAD’ -> ‘/root/media-node/.git/logs/HEAD’
‘media-node/.git/logs/refs’ -> ‘/root/media-node/.git/logs/refs’
‘media-node/.git/logs/refs/remotes’ -> ‘/root/media-node/.git/logs/refs/remotes’
‘media-node/.git/logs/refs/remotes/origin’ -> ‘/root/media-node/.git/logs/refs/remotes/origin’
‘media-node/.git/logs/refs/remotes/origin/HEAD’ -> ‘/root/media-node/.git/logs/refs/remotes/origin/HEAD’
‘media-node/.git/logs/refs/heads’ -> ‘/root/media-node/.git/logs/refs/heads’
‘media-node/.git/logs/refs/heads/master’ -> ‘/root/media-node/.git/logs/refs/heads/master’
‘media-node/.git/packed-refs’ -> ‘/root/media-node/.git/packed-refs’
‘media-node/.git/HEAD’ -> ‘/root/media-node/.git/HEAD’
‘media-node/.git/refs’ -> ‘/root/media-node/.git/refs’
‘media-node/.git/refs/tags’ -> ‘/root/media-node/.git/refs/tags’
‘media-node/.git/refs/remotes’ -> ‘/root/media-node/.git/refs/remotes’
‘media-node/.git/refs/remotes/origin’ -> ‘/root/media-node/.git/refs/remotes/origin’
‘media-node/.git/refs/remotes/origin/HEAD’ -> ‘/root/media-node/.git/refs/remotes/origin/HEAD’
‘media-node/.git/refs/heads’ -> ‘/root/media-node/.git/refs/heads’
‘media-node/.git/refs/heads/master’ -> ‘/root/media-node/.git/refs/heads/master’
‘media-node/.git/objects’ -> ‘/root/media-node/.git/objects’
‘media-node/.git/objects/info’ -> ‘/root/media-node/.git/objects/info’
‘media-node/.git/objects/pack’ -> ‘/root/media-node/.git/objects/pack’
‘media-node/.git/objects/pack/pack-328df686c9cb13dccf38e257b95f5aae3076cc5a.pack’ -> ‘/root/media-node/.git/objects/pack/pack-328df686c9cb13dccf38e257b95f5aae3076cc5a.pack’
‘media-node/.git/objects/pack/pack-328df686c9cb13dccf38e257b95f5aae3076cc5a.idx’ -> ‘/root/media-node/.git/objects/pack/pack-328df686c9cb13dccf38e257b95f5aae3076cc5a.idx’
‘media-node/.git/index’ -> ‘/root/media-node/.git/index’
‘media-node/.git/description’ -> ‘/root/media-node/.git/description’
‘media-node/.git/hooks’ -> ‘/root/media-node/.git/hooks’
‘media-node/.git/hooks/applypatch-msg.sample’ -> ‘/root/media-node/.git/hooks/applypatch-msg.sample’
‘media-node/.git/hooks/pre-rebase.sample’ -> ‘/root/media-node/.git/hooks/pre-rebase.sample’
‘media-node/.git/hooks/pre-commit.sample’ -> ‘/root/media-node/.git/hooks/pre-commit.sample’
‘media-node/.git/hooks/pre-applypatch.sample’ -> ‘/root/media-node/.git/hooks/pre-applypatch.sample’
‘media-node/.git/hooks/post-update.sample’ -> ‘/root/media-node/.git/hooks/post-update.sample’
‘media-node/.git/hooks/prepare-commit-msg.sample’ -> ‘/root/media-node/.git/hooks/prepare-commit-msg.sample’
‘media-node/.git/hooks/update.sample’ -> ‘/root/media-node/.git/hooks/update.sample’
‘media-node/.git/hooks/commit-msg.sample’ -> ‘/root/media-node/.git/hooks/commit-msg.sample’
‘media-node/.git/hooks/pre-push.sample’ -> ‘/root/media-node/.git/hooks/pre-push.sample’
spotmedias@ns:~$ 
spotmedias@ns:~$ 
spotmedias@ns:~$ TypeError: Object function createServer() {
  function app(req, res, next){ app.handle(req, res, next); }
  merge(app, proto);
  merge(app, EventEmitter.prototype);
  app.route = '/';
  app.stack = [];
  return app;
} has no method 'static'
    at Object.<anonymous> (/root/media-node/ffmpeg_server.js:383:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
Error: SQLITE_ERROR: duplicate column name: duration
Error: SQLITE_ERROR: duplicate column name: thumbs
## 

Thank you

**Comment by rahul286** [comment]
@SpotMedias we are archiving this project as this is replaced by https://rtmedia.io/transcoder/ over the years and we do not any plans to maintain this anymore. Apologies for not updating the status here.
